### ISSUE TITLE
Deploy to device fails

### ISSUE THREAD

**Issue by raulriera** [viezel/NappUI#2]
If the module is added to a project and then deployed to the iPad (device, unsure if the problem also occurs on the iPhone)

```
[ERROR] :  ** BUILD FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :   Ld build/Debug-iphoneos/[appname].app/[appname] normal armv7
[ERROR] :  (1 failure)
```

Module 1.0.1, Titanium 3.1.1

**Comment by abangjenggot** [comment]
Hi guys,

i found this error when i try to package/distribute my ios app

[ERROR] :  ** BUILD FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :  	Ld build/iVirtue.build/Release-iphoneos/iVirtue.build/Objects-normal/arm64/iVirtue normal arm64
[ERROR] :  (1 failure)

do you guys have any idea what to do?
