### ISSUE TITLE
Improper Name Used for the Toolbar tintColor Setter

### ISSUE THREAD

**Issue by juntalis** [viezel/NappUI#52]
I'm still pretty new to writing Ti extensions (and to Objective C in general) so it's completely possible that I'm wrong on this, but shouldn't the `setTintColor_` method in your [TiUIiOSToolbarProxy](https://github.com/viezel/NappUI/blob/master/Classes/TiUIiOSToolbarProxy%2BExtended.m) category be named `setTintColor`? It was my understanding that the `_` suffix is only used for properties on the View itself.

**Comment by hansemannn** [comment]
That sounds correct. So you need to call it like this?

```
Ti.UI.createToolbar({
    tintColor_: "#fff"
});
```

If so, we can simply change it and maybe deprecate it for legacy-purposes. But the properly should nowadays already be inside the Ti-Core.

**Comment by juntalis** [comment]
Sorry, I haven't really touched any Ti stuff (or Objective-C) in like a year, so I don't really remember what I was trying to do at the time or what my concern was with this. It looks like I ended up changing `setTintColor_` to `setTintColor` in my local code, but I don't know why I felt that was necessary at the time. That project was based on Ti SDK v3.4.1, though, so I wouldn't worry about it. Gonna go ahead and close this.
